### ISSUE TITLE
не приходят события от колонки

### ISSUE THREAD

**Issue by DimsonRU** [dext0r/ha-yandex-station-intents#15]
Здравствуйте,
Установил компонент, создал тестовые фразы > в приложении УДЯ создались сценарий, но текстовое событие не приходит - подписался на yandex_intent (developer-tools/event).

yandex_station_intents:
  intents:
    Включи свет в гостиной: Хорошо           
    Тест: Хорошо

**Comment by dext0r** [comment]
Колонка добавлена в комнату в УДЯ?

**Comment by DimsonRU** [comment]
Да, уже увидел что проблема была с этим - обязательно надо создать комнату и добавить туда колонку  в УДЯ.
В Интеграции яндекс станции это не обязательно.
Может стоит это выделить в описании, что бы было меньше вопросов.

Спасибо за замечательную Интеграцию!!!
