### ISSUE TITLE
Магические фразы, которые не передаются в HA

### ISSUE THREAD

**Issue by atacheev** [dext0r/ha-yandex-station-intents#16]
Добрый день,

Спасибо за классную интеграцию!

В целом у меня все работает, события отлавливаются в HA, автоматизации работают.

Столкнулся с особенностью: фраза "Свет в гостинной" не передается в HA. Колонка привязана к комнате со служебным наименованием (комнаты "гостинная" вообще нет).

Алиса на эту фразу сразу отвечает "Я и такое умею, но для этого нужны устройства умного дома Яндекс". Такое ощущение, что еще до отработки сценария колонка как-то понимает, что нет устройств управления светом и не выполняет данный сценарий.

Мог бы кто-нибудь попробовать отловить эту фразу в HA?

Мне такая фраза нужна для управления светом - если включен, то выключить, если выключен, то включить.

**Comment by dext0r** [comment]
Последнее время Яндекс что-то меняет в движке определения намерений, поэтому часть фраз из сценариев могут "просачиваться" в команды управления умным домом. Например, у меня есть сценарий на фразу "Приглуши свет". По факту на эту фразу не только выполняется сценарий, но ещё и посылается команда на включение всех светильников в комнате, к которой привязана колонка :(

Как вариант можно попробовать сделать виртуальный [светильник на шаблоне](https://www.home-assistant.io/integrations/light.template/), отдать его в УДЯ в комнату Гостиная. На команду "Свет в гостиной" УДЯ будет автоматически делать toggle в зависимости от его текущего состояния.

**Comment by dext0r** [comment]
> Столкнулся с особенностью: фраза "Свет в гостинной" не передается в HA. Колонка привязана к комнате со служебным наименованием (комнаты "гостинная" вообще нет).

Сделайте "Свет в гости**н**ой" и всё заработает :)

**Comment by atacheev** [comment]
Спасибо, так работает...  🤦‍♂️
