### ISSUE TITLE
Один аккаунт Яндекс для нескольких HA

### ISSUE THREAD

**Issue by DimsonRU** [dext0r/ha-yandex-station-intents#18]
Добрый день.
Спасибо за отличный компонент.
Столкнулся со следующей ситуацией - у меня есть один аккаунт УДЯ, в нем создано несколько домов, в каждом свои колонки.
Есть несколько инсталляция НА(т.е. один дом в УДЯ соответствует дому НА).
Активировав вашу интеграцию в нескольких домах НА, не получается создать отдельные списки фраз в yaml, свои в каждом доме - одна интеграция в НА "затирает" другую в УДЯ и наоборот(кто последний перегрузился).

Т.е. неплохо бы добавить к названиям сценариев в yaml еще и id дома. 

И от сюда вторая "проблема" - так как сценарии в УДЯ, к сожалению, не делятся по домам, а представлены общим списком, то если будет решено описанное выше, хорошо если их название будет вида "--- id_дома - название_сценария"

Заранее  Спасибо!

**Comment by dext0r** [comment]
На стороне компонента адекватно это не реализовать. Основная проблема: одинаковые сценарии, которые могут быть в обоих HA. А на стороне УДЯ проверяется уникальной активационных фраз между сценариями.

Самый простой способ выйти из ситуации - иметь абсолютно одинаковый список интентов в обоих HA, а логику ответов разруливать уже на уровне автоматизаций.
