### ISSUE TITLE
Алиса умеет различать голоса

### ISSUE THREAD

**Issue by kaizer666** [dext0r/ha-yandex-station-intents#26]
Всем дорого дня. Возник такой вопрос. 
Сейчас колонки умеют различать голоса. Есть ли возможность сделать данный функционал в рамках этой интеграции?
К примеру, на фразу ребёнка (Алиса его знает) - выполнять одно действие, на мою фразу (точно такую же) выполнять другое действие, а на эту же фразу от чужого человека - ничего не делать

**Comment by dext0r** [comment]
Яндекс не отдаётся никакой информации об распознанном голосе в тех событиях, на которых работает интеграция. Поэтом ответ - нет :(
