### ISSUE TITLE
Обработка интентов с регулярными выражениями

### ISSUE THREAD

**Issue by aldanstar** [dext0r/ha-yandex-station-intents#27]
Возможно ли сделать интенты с переменными вставками?
Например:
intents:
       На телевизоре включи *:
\* - любое продолжение, которое обрабатывается в автоматизации через регулярные выражения
Цель: Есть ТВ на платформе Яндекс.ТВ, но не ТВ от Яндекс, поэтому "тандема" до сих пор нет. Но в HA можно перебрасывать команды Алисе из ТВ от Алисы из колонки простым regex_replace(find='(На телевизоре)|(включи \S+)', replace='\\2', ignorecase=False). Все работает, но сейчас нужно писать в конфиге каждую возможную фразу, а смысла по сути в \S+ нет.

**Comment by dext0r** [comment]
В этой интеграции не получится. Посмотрите на интеграцию с Яндекс Диалогами, там возможны любые фразы - https://github.com/AlexxIT/YandexDialogs
