### ISSUE TITLE
Несколько аккаунтов Яндекс

### ISSUE THREAD

**Issue by sergmaxin** [dext0r/ha-yandex-station-intents#29]
Дома несколько колонок Яндекс на разных аккаунтах у разных членов семьи (муж,жена, дети). Очень не хватает возможности использовать YS.Intents на колонках - работает только на одной колонке

**Comment by dext0r** [comment]
Очень нетипичный кейс... А интенты должны быть общие между колонками, или у каждого свои?

**Comment by sergmaxin** [comment]
почему нетипичный? несколько колонок на разных аккаунтах- это из-за ограничений яндекса использовать одинаковые колонки на одном аккаунте. Общие интенты хотя-бы, а лучше разные. Например интенты взрослых, детей, администратора

**Comment by DmitrySinitsa** [comment]
Кейс вполне популярный для родителей с детьми 4-14 лет, приходится ставить на детские аккаунты, т.к. Алиса подмешивает популярные песни с взрослым содержимым. Возможно Яндекс как-то исправит это в будущем, но на сегодня проблема актуальна.

**Comment by brutevinch** [comment]
Реальный кейс. Сегодня настраивал и жутко расстроился что можно только один аккаунт. Кейс реальный - у ребенка своя ЯС с детским акаунтом но подключена к HA. В теории много у кого будет такая же ситуация. Было бы очень круто добавить такой функционал. Спасибо!

**Comment by DmitrySinitsa** [comment]
> Реальный кейс. Сегодня настраивал и жутко расстроился что можно только один аккаунт. Кейс реальный - у ребенка своя ЯС с детским акаунтом но подключена к HA. В теории много у кого будет такая же ситуация. Было бы очень круто добавить такой функционал. Спасибо!

Ну я в принципе обошел напрямую, через сценарии и Увеличить громкость на 0???  Работает, но конечно не удобно) Благо у детей не столько сценариев, сколько у меня)

**Comment by d51x** [comment]
У самого пристутствует такой кейс.
Есть в другой комнате у дочки яндекс колонка на ее отдельном аккаунте.

В общем я сделал 2-ую копию yandex_intents.
В папке `custom_components` копируем папку `yandex_station_intents` в `yandex_station_intents_2`.
Уже в новой папке правим файл `const.py`

```
DOMAIN = 'yandex_station_intents_2'
NOTIFICATION_TITLE = 'Yandex.Station Intents 2'
...
CONF_INTENTS = 'intents2'
...
INTENT_PLAYER_NAME = 'Yandex Station Intents 2'
...
EVENT_NAME = 'yandex_intent_2'
```


Далее в `configuration.yaml` описываем так

```
yandex_station_intents_2: 
  intents2: !include_dir_merge_named  yandex_station_intents_2/
```
в папке `yandex_station_intents_2` создаем файлики *.yaml с нужными сценариями

например, `lights.yaml`
```
Включи люстру: 

Выключи люстру:

Включи бра:

Выключи бра:

Включи ленту:

Включи ленту красным:
  extra_phrases:
    - Включи красный

Включи ленту фиолетовым:
  extra_phrases:
    - Включи фиолетовый

Включи ленту зеленым:
  extra_phrases:
    - Включи зеленый

Включи ленту синим:
  extra_phrases:
    - Включи синий

Включи ленту рыжим:
  extra_phrases:
    - Включи рыжий

Выключи ленту:

Поменяй цвет:
```
Далее уже в автоматизациях можно ловить события с типом `yandex_intent` для первой колонки 
и `yandex_intent_2` - для второй, которая на другом аккаунте.

Таким образом, вторая колонка на другом аккаунте сможет обрабатывать сценарии со своего акканута.

У меня в итоге получился такой конфиг для 2-х колонок:
```
yandex_station_intents: 
  intents: !include_dir_merge_named  yandex_station_intents_1/
yandex_station_intents_2: 
  intents2: !include_dir_merge_named  yandex_station_intents_2/
```

**Comment by DmitrySinitsa** [comment]
> У самого пристутствует такой кейс. Есть в другой комнате у дочки яндекс колонка на ее отдельном аккаунте.
> 
> В общем я сделал 2-ую копию yandex_intents. В папке `custom_components` копируем папку `yandex_station_intents` в `yandex_station_intents_2`. Уже в новой папке правим файл `const.py`
> 
> ```
> DOMAIN = 'yandex_station_intents_2'
> NOTIFICATION_TITLE = 'Yandex.Station Intents 2'
> ...
> CONF_INTENTS = 'intents2'
> ...
> INTENT_PLAYER_NAME = 'Yandex Station Intents 2'
> ...
> EVENT_NAME = 'yandex_intent_2'
> ```
> 
> Далее в `configuration.yaml` описываем так
> 
> ```
> yandex_station_intents_2: 
>   intents2: !include_dir_merge_named  yandex_station_intents_2/
> ```
> 
> в папке `yandex_station_intents_2` создаем файлики *.yaml с нужными сценариями
> 
> например, `lights.yaml`
> 
> ```
> Включи люстру: 
> 
> Выключи люстру:
> 
> Включи бра:
> 
> Выключи бра:
> 
> Включи ленту:
> 
> Включи ленту красным:
>   extra_phrases:
>     - Включи красный
> 
> Включи ленту фиолетовым:
>   extra_phrases:
>     - Включи фиолетовый
> 
> Включи ленту зеленым:
>   extra_phrases:
>     - Включи зеленый
> 
> Включи ленту синим:
>   extra_phrases:
>     - Включи синий
> 
> Включи ленту рыжим:
>   extra_phrases:
>     - Включи рыжий
> 
> Выключи ленту:
> 
> Поменяй цвет:
> ```
> 
> Далее уже в автоматизациях можно ловить события с типом `yandex_intent` для первой колонки и `yandex_intent_2` - для второй, которая на другом аккаунте.
> 
> Таким образом, вторая колонка на другом аккаунте сможет обрабатывать сценарии со своего акканута.
> 
> У меня в итоге получился такой конфиг для 2-х колонок:
> 
> ```
> yandex_station_intents: 
>   intents: !include_dir_merge_named  yandex_station_intents_1/
> yandex_station_intents_2: 
>   intents2: !include_dir_merge_named  yandex_station_intents_2/
> ```

Прикольное решение, боюсь только с обновлениями возникнут сложности. Честно говоря не так напрягает, что нельзя удобно прописать команды для детских колонок, как то, что они команды не понимают/массово исполняют.
В моем случае, если давать команду из коридора, при открытых дверях слышат 4 колонки. 2 на моем аккаунте, 2 детские. Ну и пример команды из HA "отправь пылесос на кухню" 1я выполняет, 2я игнорирует, а 3я и 4я говорят, что у них нет такого устройства. Это по началу забавно, но потом надоедает)
С помощью этого решения думаю можно пофиксить, сделав события без действия.
Но если команда не HA, таймер, погода, включи музыку - это никак не поможет. Может когда-то Яндекс позволит объединять разные аккаунты в квартиру и слышать только на 1й)

**Comment by kai-zer-ru** [comment]
У меня дома 3 колонки, все на одном аккаунте. Но каждая колонка знает голоса всех членов семьи (реализовано через "Поделиться умным домом"). Тоже ищу варианты, как отслеживать кто из членов семьи запустил сценарий. Например есть сценарии, которые могут запускать только взрослые, а дети не должны. Но такого функционала пока нет

**Comment by dext0r** [comment]
Реализовано в 0.6.0
