### ISSUE TITLE
Ошибка подключения к УДЯ

### ISSUE THREAD

**Issue by eratnik** [dext0r/ha-yandex-station-intents#30]
С неделю-две назад как-то незаметно перестала работать интеграция. Запись добавляется (и через Yandex.Station, и через куки), но пишет, что нет устройств (при этом в интеграции Yandex.Station есть три устройства). Пробовал удалить добавить/ Также пробовал скачать повторно в HACS. Ничего из этого не помогло.
[![Screenshot-1.png](https://i.postimg.cc/TY4cWjpX/Screenshot-1.png)](https://postimg.cc/Czb83qGv)
Версия интеграции: 0.5.0
<details>
  <summary>лог ошибки</summary>
  
Logger: custom_components.yandex_station_intents.yandex_quasar
Source: custom_components/yandex_station_intents/yandex_session.py:180
Integration: Yandex.Station Intents ([documentation](https://github.com/dext0r/ha-yandex-station-intents), [issues](https://github.com/dext0r/ha-yandex-station-intents/issues))
First occurred: 6 августа 2023 г. в 13:46:34 (31 occurrences)
Last logged: 12:10:52

Ошибка подключения к УДЯ
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1085, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1069, in create_connection
    sock = await self._connect_sock(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 973, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.11/asyncio/selector_events.py", line 634, in sock_connect
    return await fut
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/selector_events.py", line 674, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('::', 443, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/yandex_station_intents/yandex_quasar.py", line 270, in connect
    self._ws = await self._session.ws_connect(url, heartbeat=45)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/yandex_station_intents/yandex_session.py", line 180, in ws_connect
    return await self._session.ws_connect(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 779, in _ws_connect
    resp = await self.request(
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 536, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 1209, in _create_direct_connection
    raise last_exc
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 1178, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host push.yandex.ru:443 ssl:default [Connect call failed ('::', 443, 0, 0)]
</details>

<details>
  <summary>информация о системе</summary>

Версия | core-2023.7.3
-- | --
Тип установки | Home Assistant OS
Среда разработки | false
Supervisor | true
Docker | true
Пользователь | root
Виртуальное окружение | false
Версия Python | 3.11.4
Семейство операционных систем | Linux
Версия операционной системы | 6.1.39
Архитектура ЦП | x86_64

</details>

**Comment by dext0r** [comment]
> но пишет, что нет устройств

Это нормально, интеграция не создаёт устройств.

> aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host push.yandex.ru:443 ssl:default [Connect call failed ('::', 443, 0, 0)]

Компонент не может подключиться на сервера Яндекса. Вы в России? Или может VPN какой? Через браузер и тот же интернет что на HA вы можете зайти на https://push.yandex.ru? (должно быть `The requested URL was not found`)

**Comment by eratnik** [comment]
> > но пишет, что нет устройств
> 
> Это нормально, интеграция не создаёт устройств.
> 
> > aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host push.yandex.ru:443 ssl:default [Connect call failed ('::', 443, 0, 0)]
> 
> Компонент не может подключиться на сервера Яндекса. Вы в России? Или может VPN какой? Через браузер и тот же интернет что на HA вы можете зайти на https://push.yandex.ru? (должно быть `The requested URL was not found`)

Я из Беларуси. VPN на этом устройстве нет. На уровне роутера (keenetic) стоит фильтрация через dns (nextdns) - пробовал отключать, добавил *push.yandex.ru в исключения, но ничего не меняется.
При переходе через браузер на https://push.yandex.ru пишет `The requested URL was not found`.
Что интересно - решил наоборот включить для сервера VPN - заработало как в регион РФ, так и на европейских. Получается проблема с моим провайдером?

**Comment by dext0r** [comment]
> Получается проблема с моим провайдером?

Скорее всего. Для диагностики доступности push.yandex.ru:
* Подключитесь по SSH к вашему HA
* Выполните команду `curl https://push.yandex.ru`. При доступности будет выведено `The requested URL was not found`, в противном случае - ошибка (таймаут и т.п.)

Ишью закрываю, так как проблема не относится к компоненту.
