### ISSUE TITLE
Ошибка создания или обновления сценария

### ISSUE THREAD

**Issue by perfect-deform** [dext0r/ha-yandex-station-intents#33]
Здравствуйте. В УДЯ станции присвоена комната. Сценарии в УДЯ добавились. Но при перезагрузке конфигурации YAML падает ошибка и автоматизации не создаются. Сообщения не приходят.

```Logger: custom_components.yandex_station_intents
Source: custom_components/yandex_station_intents/__init__.py:248
Integration: Yandex.Station Intents ([documentation](https://github.com/dext0r/ha-yandex-station-intents), [issues](https://github.com/dext0r/ha-yandex-station-intents/issues))
First occurred: 00:37:17 (2 occurrences)
Last logged: 00:37:17

Ошибка создания или обновления сценария '--- Как дела'
Ошибка создания или обновления сценария '--- Кто нибудь дома'
Traceback (most recent call last):
  File "/config/custom_components/yandex_station_intents/__init__.py", line 248, in _async_setup_intents
    await quasar.async_add_or_update_intent(
  File "/config/custom_components/yandex_station_intents/yandex_quasar.py", line 201, in async_add_or_update_intent
    r = await self._session.put(f'{URL_USER}/scenarios/{intent_quasar_id}', json=payload)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/yandex_station_intents/yandex_session.py", line 174, in put
    return await self._request('put', url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/yandex_station_intents/yandex_session.py", line 195, in _request
    r = await getattr(self._session, method)(url, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 400, in _request
    raise RuntimeError("Session is closed")
RuntimeError: Session is closed
```

В /config/configuration.yaml
```
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

yandex_station_intents:
  intents:
    Как дела:
    Кто нибудь дома: Сейчас проверю
```

**Comment by dext0r** [comment]
Воспроизвести не получается. Подскажите версию HA и как он запущен? (HASS OS или что-то другое?)

**Comment by perfect-deform** [comment]
> Воспроизвести не получается. Подскажите версию HA и как он запущен? (HASS OS или что-то другое?)

Home Assistant 2023.10.1
Supervisor 2023.10.1.dev0501
Пользовательский интерфейс 20231005.0 - latest

Запущен в docker контейнере на Orange pi под управлением debian_bookworm_server_linux6.1.31

**Comment by VikeDragon** [comment]
Добрый день dext0r !

Home assistant в proxmox

Core
2024.3.1
Supervisor
2024.03.0
Operating System
12.1
Пользовательский интерфейс
20240307.0

получаю аналогичные ошибки :

Эта ошибка возникла в пользовательской интеграции.

Регистратор: custom_components.yandex_station_intents
Источник: custom_components/yandex_station_intents/__init__.py:248
интеграция: Yandex.Station Intents (документация, проблемы)
Первое сообщение: 18:04:03 (13 сообщений)
Последнее сообщение: 18:04:30

Ошибка создания или обновления сценария '--- Включи Автосвет в спальне'
Ошибка создания или обновления сценария '--- Выключи Автосвет в спальне'
Ошибка создания или обновления сценария '--- Придет гость'
Ошибка создания или обновления сценария '--- Быстрая сушка ножей'
Ошибка создания или обновления сценария '--- Полей калатею малую'
Traceback (most recent call last):
  File "/config/custom_components/yandex_station_intents/__init__.py", line 248, in _async_setup_intents
    await quasar.async_add_or_update_intent(
  File "/config/custom_components/yandex_station_intents/yandex_quasar.py", line 207, in async_add_or_update_intent
    assert resp['status'] == 'ok', resp
AssertionError: {'request_id': '1caa13c3-d7c6-4db8-9a00-7cfd35a8c357', 'status': 'error', 'code': 'VOICE_TRIGGER_PHRASE_IS_ALREADY_TAKEN', 'message': 'Активационная фраза для сценария уже используется'}

**Comment by dext0r** [comment]
> Впечатление, что повторно пытается зарегистрировать фразы.

А эти фразы точно в других сценариях не используются? Проверяли через Дом с Алисой? 
Больше на эту проблему никто не жаловался.

**Comment by altapo** [comment]
После добавления новой фразы, тоже стал ловить ошибки вида:
```
2024-04-16 21:32:50.867 ERROR (MainThread) [custom_components.yandex_station_intents] Ошибка создания или обновления сценария '--- Включи свет в коридоре'
Traceback (most recent call last):
File "/config/custom_components/yandex_station_intents/__init__.py", line 248, in _async_setup_intents
await quasar.async_add_or_update_intent(
File "/config/custom_components/yandex_station_intents/yandex_quasar.py", line 207, in async_add_or_update_intent
assert resp['status'] == 'ok', resp
AssertionError: {'request_id': '091dd513-54a6-4efd-8af1-96056aa3f8df', 'status': 'error', 'code': 'VOICE_TRIGGER_PHRASE_IS_ALREADY_TAKEN', 'message': 'Активационная фраза для сценария уже используется'}
```
проверил, активационные фразы вызывающие ошибки точно не используются, очистил все сценарии - теперь отвалилась добрая половина фраз 

Предполагаю возможное кеширование фраз на стороне яндекса, но это конечно догадки :/
