### ISSUE TITLE
Можно ли сделать переменную в навыке 

### ISSUE THREAD

**Issue by DenHeat** [dext0r/ha-yandex-station-intents#34]
Интересует возможность создания переменной при активации автоматизации 
Хочется сделать её на порядок умнее 
Тоесть после её вопроса я ответил 8 утра к примеру, и далее мне нужно это значение подставить в следующую автоматизацию которая ставит будильник (опять же к примеру)

**Comment by dext0r** [comment]
Фразы для активации интентов могут быть только фиксированными, поддержка "переменных" невозможна из-за особенностей механизма, на котором интенты работают. 
Если я правильно понял, вашу задачу можно решить интеграция с Яндекс Диалогами - https://github.com/AlexxIT/YandexDialogs

**Comment by DenHeat** [comment]
В любом случае спасибо,я знаю как можно решить по другому мою проблему (больше автоматизаций богу автоматизаций ) .
А если сталкивались ,вроде в какой-то интеграции создавалась переменная в которой всё что Алиса услышала при последней активации . Или я ошибаюсь (давно это было )

**Comment by dext0r** [comment]
> вроде в какой-то интеграции создавалась переменная в которой всё что Алиса услышала при последней активации

На данный момент нет известных способов как-то узнать что конкретно услышала Алиса.

**Comment by DenHeat** [comment]
Эх печально, спасибо
