### ISSUE TITLE
Возможность разбить конфигурацию yandex_station_intents на несколько полей

### ISSUE THREAD

**Issue by klonwar** [dext0r/ha-yandex-station-intents#36]
**Описание:**

https://www.home-assistant.io/docs/configuration/splitting_configuration/#example-combine-include_dir_merge_list-with-automationsyaml

Home Assistant позволяет разбивать конфигурацию таким способом:
```
# My own handmade automations
automation manual: !include_dir_merge_list automations/

# Automations I create in the UI
automation ui: !include automations.yaml
```
То есть, я могу смержить несколько разных директорий/файлов в одно поле конфигурации, указав разные "метки" после названия поля.

**Запрос:**
Хотелось бы иметь такую же возможность для yandex_station_intents:
```
yandex_station_intents feature1:
  intents: !include_dir_merge_named src/features/feature1/intents

yandex_station_intents feature2:
  intents: !include_dir_merge_named src/features/feature2/intents
```

Или даже

```
yandex_station_intents:
  intents feature1: !include_dir_merge_named src/features/feature1/intents
  intents feature2: !include_dir_merge_named src/features/feature2/intents
```

**Причина:**
Со временем число конфигураций разрастается и становится сложнее добавлять что-то новое в свой умный дом, не запутавшись в миллионах файлов и конфигураций. Разбиение конфигов по фичам сделает процесс добавления новой функциональности более простым, а структуру директорий более красивой.

**Референсы:**
Если я все правильно понял, то [здесь](https://github.com/home-assistant/core/blob/24ddc939c0e894b1a30d0fec33518c84357a4d08/homeassistant/components/automation/config.py#L264C49-L264C49) как раз в цикле пробегаются по всем "платформам", то есть меткам "automation". 

* [domain_key](https://github.com/home-assistant/core/blob/24ddc939c0e894b1a30d0fec33518c84357a4d08/homeassistant/helpers/config_validation.py#L354) - делает "automation" из "automation 1"
* [config_per_platform](https://github.com/home-assistant/core/blob/dev/homeassistant/config.py#L1288) - позволяет пробежаться по всем разбитым конфигам, зная только DOMAIN
* [async_validate_config](https://github.com/home-assistant/core/blob/24ddc939c0e894b1a30d0fec33518c84357a4d08/homeassistant/components/automation/config.py#L264) - пример использования, проверка конфига с таким разбиением на несколько меток
* Чуть по другому то же самое выпоняется для [скриптов](https://github.com/home-assistant/core/blob/dc10f3c204e0e94e958f3b71c0fcb1caab12e1ce/homeassistant/components/script/config.py#L261)

Если это переиспользовать, то по идее можно достаточно просто добавить поддержку подобного синтаксиса, ничего при этом не сломав.

**Comment by Tynianoff** [comment]
А чем Вас не устраивают пакаджи в Home Assistant? Создал для каждой комнаты отдельный файл с интентами.

**Comment by klonwar** [comment]
Хм, действительно. Что-то я упустил эту фичу при чтении доки) Завтра попробую на них свой конфиг переписать

**Comment by klonwar** [comment]
Packages полностью подходят, спасибо!

**Comment by Tynianoff** [comment]
> Packages полностью подходят, спасибо!

Рад помочь 🙂🤝
