### ISSUE TITLE
Расширить описание для подключения через mode=device

### ISSUE THREAD

**Issue by pakinmaksim** [dext0r/ha-yandex-station-intents#42]
Лично у меня при подключении служебного плеера в УДЯ (Yandex Station Intents) была проблема:

> Служебный плеер Yandex Station Intents не найден в УДЯ. Убедитесь, что он разрешён в фильтрах в компоненте Yandex Smart Home, обновите список устройств в УДЯ и перезагрузите эту интеграцию.

В целом ошибка описывает проблему нормально, но непонятно, что делать. При синхронизации устройств в УДЯ возникает окно настройки этого служебного плеера. Яндекс просит переименовать это устройство, чтобы им можно было пользоваться голосом, т.е. название должно быть русским. Через некоторое время обнаружил, что это окно можно проигнорировать, хотя Яндекс и пометит устройство, что его нужно настроить

Предлагаю добавить в ReadMe пометку по этому поводу. Или указать, как назвать на русском этот плеер, чтобы Яндекс не бесил надписью "Требуется настройка". Только тогда надо будет немного расширить поиск вот [здесь](https://github.com/dext0r/ha-yandex-station-intents/blob/b8b1fb8bafb3f370fbf06466064d5f094dd0e831/custom_components/yandex_station_intents/yandex_quasar.py#L145)

Просто хочу описать проблему, в целом можно её проигнорировать.

**Comment by pakinmaksim** [comment]
Или, допустим, использовать для поиска оригинальное название, а не основное. Если открыть устройство в УДЯ, то видно, что оригинальное название хранится. Может и запросить его можно

**Comment by dext0r** [comment]
Спасибо за фидбек. Планирую переделать поиск служебного плеера чтобы не зависеть от его имени. 

Вообще mode=device это старый способ, который оставлен "на всякий случай". Подскажите, зачем вы его используете? Чем не устраивает дефолтный websocket?
