### ISSUE TITLE
Intent "включи подсветку" на Yandex midi

### ISSUE THREAD

**Issue by paulcrybaby** [dext0r/ha-yandex-station-intents#45]
Сейчас при команде "включи подсветку" (или "выключи подсветку") на всех колонках в доме кроме Яндекс миди - корректно пробрасывается intent и можно настроить автоматизацию, а вот на Яндекс миди на эту команду просто включается/отключается led подсветка на самой колонке. Можно ли это как-то победить?

Спасибо

**Comment by dext0r** [comment]
На данный момент такой сценарий успешно работает:

<img width="401" alt="Screenshot 2024-10-12 at 10 31 07" src="https://github.com/user-attachments/assets/e8ce076d-9739-4e2e-bd7d-c0f3f99e3c5d">

Скорее всего проблема уже решена на стороне Яндекса. Кроме того, у меня есть устройство с названием "подсветка", и Миди всегда его успешно включала.
